### ISSUE TITLE
Rundungsfehler

### ISSUE THREAD

**Issue by ghost** [ecmonline/invoice-generator#1]
Servus,

ich glaube da ist ein kleiner Rundungsfehler. Folgendes Beispiel

| Beschreibung        | Wert           |
| ------------- |:-------------:|
| Bruttopreis      | 0,99 € |
| Steuern (19%)     | 0,16 €     |  
| Netto | 0,83 €      |  

Bei dem Generator habe ich dann folgende Daten gepflegt:

```yaml
positions:
    - netto_price: 0.83 
      amount: 10
      text: |
        Server Rechenzentrum
        Windows Server
```
Wo ja dann ein Gesamtwert von 9,90 € raus kommen müsste.
Es kommt aber folgendes bei rum:
![pic](https://user-images.githubusercontent.com/7816755/34648505-a736f294-f39a-11e7-9955-e3c57f93bf50.png)

Es fehlen also irgendwo 2 Cent.
